apiVersion: lb.scaleway.upbound.io/v1alpha1
kind: Frontend
metadata:
  name: lb-frontend
spec:
  forProvider:
    name: crossplane-lb-frontend
    lbIdRef:
      name: lb-instance
    backendIdRef:
      name: lb-backend
    inboundPort: 8080
  providerConfigRef:
    name: default
---
apiVersion: lb.scaleway.upbound.io/v1alpha1
kind: Backend
metadata:
  name: lb-backend
spec:
  forProvider:
    name: crossplane-lb-backend
    lbIdRef:
      name: lb-instance
    forwardProtocol: http
    forwardPort: 80
  providerConfigRef:
    name: default
---
apiVersion: lb.scaleway.upbound.io/v1alpha1
kind: LB
metadata:
  name: lb-instance
spec:
  forProvider:
    name: crossplane-lb-instance
    type: LB-S
    ipIdRef:
      name: lb-ip
  providerConfigRef:
    name: default
---
apiVersion: lb.scaleway.upbound.io/v1alpha1
kind: IP
metadata:
  name: lb-ip
spec:
  forProvider: {}
  providerConfigRef:
    name: default
