# Scaleway AK/SK secret allowing crossplane to communicate with scaleway api's
apiVersion: v1
kind: Secret
metadata:
  name: scw-creds
  namespace: upbound-system
type: Opaque
stringData:
  credentials: |
    {
      "access_key": "REDACTED",
      "secret_key": "REDACTED",
      "project_id": "REDACTED",
      "region": "fr-par",
      "zone": "fr-par-1"
    }
